### ISSUE TITLE
Compatibility to JSON Schema validation

### ISSUE THREAD

**Issue by NickNaso** [fabioricali/valify#7]
What do you think of the idea of making **valify** compatible with JSON Schema specifications like reported here:
https://github.com/json-schema-org/JSON-Schema-Test-Suite

So the library could be used with minimum impact to replace others.

**Comment by fabioricali** [comment]
Hi Nick!
thanks for your message!
I think that JSON Schema is a bit complex so I have decided to make a simple key/value structure. However it could be done...

**Comment by NickNaso** [comment]
I agree with you so for now I close the issue and maybe in the future if requested reconsider this.
